version: "2"
run:
  timeout: 5m
  tests: false

linters:
  default: fast
  disable:
    - errcheck
    - depguard
    - mnd
    - tagalign

  settings:
    lll:
      line-length: 150
    gocyclo:
      min-complexity: 20
    cyclop:
      max-complexity: 20
    funlen:
      lines: 100
      statements: 50

output:
  format: colored-line-number
