version: '3.8'

services:
  seedbox-downloader:
    build: .
    environment:
      # Application config
      - DOWNLOAD_CLIENT=putio
      - PUTIO_TOKEN=${PUTIO_TOKEN}
      - PUTIO_BASE_DIR=/downloads
      - TARGET_LABEL=seedbox
      - DOWNLOAD_DIR=/downloads
      - POLLING_INTERVAL=5m
      - LOG_LEVEL=INFO

      # Telemetry config
      - TELEMETRY_ENABLED=true
      - TELEMETRY_METRICS_ADDRESS=0.0.0.0:2112
      - TELEMETRY_METRICS_PATH=/metrics
      - TELEMETRY_SERVICE_NAME=seedbox_downloader

      # Web config
      - WEB_BIND_ADDRESS=0.0.0.0:9091
    ports:
      - "9091:9091" # Main API
      - "2112:2112" # Metrics endpoint
    volumes:
      - ./downloads:/downloads
      - ./data:/data
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - monitoring
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:


networks:
  monitoring:
    driver: bridge
