version: "2"
run:
  timeout: 5m

linters:
  default: fast
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - structcheck
    - deadcode
    - typecheck
    - ineffassign
    - varcheck
    - revive
    - gofmt
    - goimports
    - misspell
    - depguard
    - gocritic
    - dupl
    - unparam
    - nakedret
    - dogsled
    - exportloopref
    - gocyclo
    - interfacer
    - lll
    - prealloc
    - scopelint
    - stylecheck
    - whitespace
  disable:
    - errcheck

output:
  format: colored-line-number

exclusions:
  rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
